---
abstract: 'LWP methods implementation with Curl engine'
author:
  - 'Lindolfo Rodrigues de Oliveira Neto, C<< <lorn at cpan.org> >>'
  - 'Lindolfo Rodrigues de Oliveira Neto <lorn@cpan.org>'
build_requires:
  Carp: 0
  ExtUtils::MakeMaker: 6.42
  Test::Exception: 0
  Test::More: 0
  URI::Escape: 0
  URI::file: 0
  WWW::Curl::Easy: 0
configure_requires:
  ExtUtils::MakeMaker: 6.42
distribution_type: module
generated_by: 'Module::Install version 1.00'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: LWP-Curl
no_index:
  directory:
    - inc
    - t
resources:
  license: http://dev.perl.org/licenses/
version: 0.08
